source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'activerecord', require: 'active_record'

group :development, :test do
  # Use SQLite for ActiveRecord
  gem 'sqlite3'
  gem 'pry'
end

group :test do
  gem 'rspec'
  gem "rack-test"
  gem "database_cleaner"
  gem "shoulda-matchers"
  gem 'factory_girl'
end
